Target=E:\Games\Rain World\RainWorld.exe
HELP=..\profiles\rain world.ini
wiki=https://www.pcgamingwiki.com/wiki/Rain_World
D3D=11
Path=Rainworld
WSTL=0
DMWM=0
Gamma=0
NEFS=0
32bit=0
HD=1
DSR=False
xBR=0
HLFPX=0
WHKS=true
MHKS=false
MCLP=0
FLTR=0
SYNC=0
SXTY=0
VPOS=False
POW2=False
PixelSwap=false
TextureSwap=true
RDSK=3
RLMT=0
 
[<Gpad>]
A=1
B=2
X=3
Y=4
LEFT_SHOULDER=5
RIGHT_SHOULDER=6
bLeftTrigger=7
bRightTrigger=8
Start=9
Back=10
LEFT_THUMB=11
RIGHT_THUMB=12
deadzone=0.25
 
[J2K]
u=False
a=,,,,,,,,,,,,,,,,,,,
b=,,,,,,,,,,,,,,,,,,,
x=,,,,,,,,,,,,,,,,,,,
y=,,,,,,,,,,,,,,,,,,,
mds=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
m=0
spd=0
dz=0.25
 
[Textswap]
s=4
sz=256
path=Textures\VOKSI
n=PgUP
p=PgDn
d=Home
sw=End
c=Del
q=Ins
y=0
e=true
 
[PxSwap]
s=u
sw=Alt
;dev=1
n=<
p=>
d=ins 
e=true
[help] 
::Title::Rain World::
{h1 Fixes and improvements} 
{f [gototab_graphics_HD=UPSCALE Nearest neighbor upscaling] will prevent the game from 
looking blurry on monitors with resolution over 1366x768 and requires the 
[gototab_graphics_RLMT limit resolutions] option set at that value}
{f [gototab_graphics_HD=UPSCALE FidelityFx super resolution] upscaling can also 'fix' 
the pixelation if your not a fan of pixelart, but then the game will remain 
blurry}
{b  {f} ==[The game is not upscaled correctly]==
this can happen evry other time you start the game, if ti does, just start the 
game again}
%dx11%
 
